resilience4j:
  circuitbreaker:
    configs:
      gateway_default:  #Es solamente un nombre que yo le asigno
        sliding-window-size: 6 #Seis intentos, porque ajá
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s  #Es sumamente importante especificar la unidad de tiempo
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s  #Es sumamente importante especificar la unidad de tiempo
        slow-call-rate-threshold: 50
    instances:
      products: #Busca el circuit breaker con nombre products
        base-config: gateway_default  #Asigna la configuración de nombre gateway_default en la instancia llamada products
  time-limiter:
    configs:
      gateway_default:  #Es solamente un nombre que yo le asigno
        timeout-duration: 4s  #Es sumamente importante especificar la unidad de tiempo
    instances:
      products: #Busca el circuit breaker con nombre products
        base-config: gateway_default  #Asigna la configuración de nombre gateway_default en la instancia llamada products

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9100
      client:
        registration:
          client-app:
            provider: spring
            client-id: gateway-app
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/authorized
            scope:
            - openid
            - profile
    #       - read
    #       - write
            client-name: client-app
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9100

  cloud:
    gateway:
      mvc:
        routes:
          - id: msvc-products
            uri: lb://msvc-products
            predicates:
            - Path=/api/products/**
    #       - Header=token, ^[a-zA-Z0-9A-Z0-9]+(-[a-zA-Z0-9]+)*$
    #       - Method=GET, POST
    #       - Query=color, verde  #Si no se envía el parámetro «color» con el valor «azul», se arroja un 404
    #       - Cookie=color, azul
            filters:
    #       - StripPrefix=2
    #       - ExempleCookie=user-cookie, Santiago, pero mira qué mensaje personalizado tan bonito
    #       - CircuitBreaker=products
            - name: CircuitBreaker #Tiene que ir este nombre (filtro de fábrica de Spring Framework)
              args:
                name: products  #Este es el ID que le asigno a este cortocircuito
                statusCodes: 500  #Recordar que maneja varios
                fallbackUri: forward:/api/items/4 #De aquí la importancia de tener rutas libres relacionadas al microservicio que puede fallar. Mandarlo al mismo puede generar un bucle infinito
#           - name: SampleCookie #Va sólo el prefijo del filtro personalizado
#             args:
#               name: user-cookie
#               value: Santiago
#               message: pero mira qué mensaje personalizado tan bonito
          - id: msvc-items
            uri: lb://msvc-items
            predicates:
              - Path=/api/items/**
            filters:
    #       - StripPrefix=2
            - AddRequestHeader=token-request, buajuajuajua
            - AddResponseHeader=token-response, mambrú volviendo de la guerra
            - AddRequestParameter=name, QuesoColo
            - SetResponseHeader=Content-Type, text/plain  #application/json
          - id: msvc-users
            uri: lb://msvc-users
            predicates:
            - Path=/api/usagers/**
            filters:  #De momento, no se le configura ningún filtro
          - id: msvc-OAuth2
            uri: lb://msvc-OAuth2
            predicates:
            - Path=/api/security/**
            filters:
            - StripPrefix=2
